[package]
name = "gmboy"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[features]
default = []

[dependencies.sdl2]
version = "0.37"
default-features = false
features = ["unsafe_textures"] #"bundled"

[dependencies]
serde_json = "*"
serde = { version = "*", features = ["derive"] }

[dev-dependencies]
criterion = "*"

[[bench]]
name = "bench"
harness = false

# This section is not strictly necessary unless you're using specific build dependencies
[build-dependencies]
