[package]
name = "gmboy"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[features]
default = []

[dependencies.sdl2]
version = "0.37"
default-features = false
features = ["bundled", "unsafe_textures"]

[dependencies]

[dev-dependencies]
criterion = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"

[[bench]]
name = "bench"
harness = false
