[package]
name = "rusty-gb-emu"
version = "0.1.0"
edition = "2021"


[features]
default = []
cpu_debug = []  # Add a feature to enable CPU_DEBUG

[dependencies]

[dev-dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
