[package]
name = "android"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[lib]
name = "gmboy"
crate-type = ["cdylib", "rlib"]

[dependencies]
app = { path = "../app" }
