[package]
name = "android"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[lib]
name = "main"
crate-type = ["cdylib"]

[dependencies]
core = { path = "../core", default-features = false }
app = { path = "../app", default-features = false }
jni = "0.21"