name: Build linux ARM release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build-arm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu zip
          rustup target add aarch64-unknown-linux-gnu

      - name: Build for ARM
        env:
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
          AR_aarch64_unknown_linux_gnu: aarch64-linux-gnu-ar
          RUSTFLAGS: "-C linker=aarch64-linux-gnu-gcc"
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: cargo build --release --target=aarch64-unknown-linux-gnu -p desktop

      - name: Prepare ARM release
        run: |
          mkdir -p dist
          cp target/aarch64-unknown-linux-gnu/release/gmboy dist/

      - name: List files in dist
        run: ls -la dist

      - name: Zip ARM release
        run: cd dist && zip -r gmboy-linux-aarch64.zip .

      - name: Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: gmboy-linux-aarch64.zip
          path: dist/gmboy-linux-aarch64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gmboy-linux-aarch64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
