name: Build windows release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]
    
jobs:
  build-windows:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 curl zip

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Download SDL2 for Windows
        run: |
          curl -LO https://www.libsdl.org/release/SDL2-devel-2.28.5-mingw.tar.gz
          tar -xzf SDL2-devel-2.28.5-mingw.tar.gz
          mv SDL2-2.28.5/x86_64-w64-mingw32 /opt/SDL2-win

      - name: Build Windows release
        env:
          LIBRARY_PATH: /opt/SDL2-win/lib
          C_INCLUDE_PATH: /opt/SDL2-win/include
          PKG_CONFIG_ALLOW_CROSS: "1"
          SDL2_DIR: /opt/SDL2-win
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Prepare release files
        run: |
          mkdir -p dist/windows
          cp target/x86_64-pc-windows-gnu/release/gmboy.exe dist/windows/
          cp /opt/SDL2-win/bin/SDL2.dll dist/windows/
          cp config.json dist/windows/

      - name: Zip Windows release
        run: cd dist && zip -r gmboy-windows.zip windows

      - name: Upload Windows zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gmboy-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
