name: Build macOS Release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-macos:
    if: github.event_name == 'release'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install targets
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin -p desktop

      - name: Build universal binary
        run: |
          cargo build --release --target=aarch64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          mkdir -p target/universal/release
          lipo -create -output target/universal/release/gmboy \
            target/aarch64-apple-darwin/release/gmboy \
            target/x86_64-apple-darwin/release/gmboy

      - name: Prepare macOS release files
        run: |
          mkdir -p dist
          cp target/universal/release/gmboy dist/

      - name: Zip bundle
        run: cd dist && zip -r gmboy-macos-universal.zip .

      - name: Upload Linux zip to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gmboy-macos-universal.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
