name: Build windows release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]
    
jobs:
  build-windows:
    if: github.event_name == 'release'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
      
      - name: Download SDL2 DLL for Windows
        run: |
          curl -L -o SDL2.zip https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-VC.zip
          mkdir SDL2
          tar -xf SDL2.zip -C SDL2
          copy SDL2\lib\x64\SDL2.dll dist\windows\
      
      - name: Build Release
        run: cargo build --release --target x86_64-pc-windows-msvc
      
      - name: Prepare release files
        run: |
          mkdir dist\windows
          copy target\x86_64-pc-windows-msvc\release\gmboy.exe dist\windows\
          copy "C:\tools\SDL2\bin\SDL2.dll" dist\windows\
          copy target\x86_64-pc-windows-msvc\release\config.json dist\windows\
      
      - name: Zip Windows release
        run: powershell Compress-Archive -Path dist\windows\* -DestinationPath dist\gmboy-windows.zip
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist\gmboy-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
