name: Build macos release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build-macos:
    if: github.event_name == 'release'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install SDL2
        run: brew install sdl2 zip

      - name: Set environment variables for SDL2
        run: |
          echo "LIBRARY_PATH=$(brew --prefix sdl2)/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix sdl2)/lib/pkgconfig" >> $GITHUB_ENV
          echo "CFLAGS=-I$(brew --prefix sdl2)/include" >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix sdl2)/lib" >> $GITHUB_ENV

      - name: Build for macOS
        run: cargo build --release

      - name: Prepare macOS release
        run: |
          mkdir -p dist
          cp target/release/gmboy dist/

      - name: Prepare macOS release as .app bundle
        run: |
          mkdir -p dist/gmboy.app/Contents/MacOS
          mkdir -p dist/gmboy.app/Contents/Resources
          mkdir -p dist/gmboy.app/Contents/Frameworks
          cp target/release/gmboy dist/gmboy.app/Contents/MacOS/gmboy
          cp $(brew --prefix sdl2)/lib/libSDL2-2.0.0.dylib dist/gmboy.app/Contents/Frameworks/
          install_name_tool -change "$(brew --prefix sdl2)/lib/libSDL2-2.0.0.dylib @executable_path/../Frameworks/libSDL2-2.0.0.dylib" dist/gmboy.app/Contents/MacOS/gmboy
          
          cat > dist/gmboy.app/Contents/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>CFBundleName</key>
              <string>gmboy</string>
              <key>CFBundleDisplayName</key>
              <string>gmboy</string>
              <key>CFBundleIdentifier</key>
              <string>com.troidem.gmboy</string>
              <key>CFBundleVersion</key>
              <string>0.1</string>
              <key>CFBundleExecutable</key>
              <string>gmboy</string>
              <key>CFBundlePackageType</key>
              <string>APPL</string>
            </dict>
          </plist>
          EOF

      - name: Zip macOS release
        run: cd dist && zip -r gmboy-macos.zip gmboy.app

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gmboy-macos-app
          path: dist/gmboy-macos.zip

