name: Build windlows release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build-windows:
    if: github.event_name == 'release'
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SDL2 (via vcpkg)
      run: |
        git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat
        C:\vcpkg\vcpkg.exe install sdl2 sdl2-image sdl2-mixer sdl2-ttf
        echo "VCPKG_ROOT=C:\\vcpkg" >> $GITHUB_ENV

    - name: Set RUSTFLAGS for SDL2 linking
      run: echo "RUSTFLAGS=-L C:\\vcpkg\\installed\\x64-windows\\lib" >> $env:GITHUB_ENV
      shell: powershell

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-msvc
        override: true

    - name: Build release
      run: cargo build --release

    - name: Prepare release folder
      run: |
        mkdir dist
        copy target\release\gmboy.exe dist\
        copy C:\vcpkg\installed\x64-windows\bin\SDL2.dll dist\

    - name: Zip release folder
      run: |
        powershell Compress-Archive -Path dist\* -DestinationPath gmboy-windows.zip

    - name: Upload zip to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: gmboy-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
