name: Build macOS Release

on:
  release:
    types: [published]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install targets
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Build universal binary
        run: |
          cargo build --release --target=aarch64-apple-darwin
          cargo build --release --target=x86_64-apple-darwin
          mkdir -p target/universal/release
          lipo -create -output target/universal/release/gmboy \
            target/aarch64-apple-darwin/release/gmboy \
            target/x86_64-apple-darwin/release/gmboy

      - name: Create .app bundle
        run: |
          mkdir -p dist/gmboy.app/Contents/MacOS
          mkdir -p dist/gmboy.app/Contents/Resources
          cat > dist/gmboy.app/Contents/Info.plist <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
            <key>CFBundleName</key>
            <string>gmboy</string>
            <key>CFBundleDisplayName</key>
            <string>gmboy</string>
            <key>CFBundleIdentifier</key>
            <string>com.troidem.gmboy</string>
            <key>CFBundleVersion</key>
            <string>0.1</string>
            <key>CFBundleExecutable</key>
            <string>gmboy</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            </dict>
            </plist>
            EOF
          cp target/universal/release/gmboy dist/gmboy.app/Contents/MacOS/gmboy

      - name: Zip bundle
        run: cd dist && zip -r gmboy-macos.zip gmboy.app

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gmboy-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
