name: Build linux ARM release

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: aarch64
            rust_target: aarch64-unknown-linux-gnu
            gcc_pkg: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            cc_var: CC_aarch64_unknown_linux_gnu
            cxx_var: CXX_aarch64_unknown_linux_gnu
            ar_var: AR_aarch64_unknown_linux_gnu
            cc_bin: aarch64-linux-gnu-gcc
            cxx_bin: aarch64-linux-gnu-g++
            ar_bin: aarch64-linux-gnu-ar
            out_name: gmboy-linux-aarch64.zip
          - arch: armv7
            rust_target: armv7-unknown-linux-gnueabihf
            gcc_pkg: gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
            cc_var: CC_armv7_unknown_linux_gnueabihf
            cxx_var: CXX_armv7_unknown_linux_gnueabihf
            ar_var: AR_armv7_unknown_linux_gnueabihf
            cc_bin: arm-linux-gnueabihf-gcc
            cxx_bin: arm-linux-gnueabihf-g++
            ar_bin: arm-linux-gnueabihf-ar
            out_name: gmboy-linux-armv7.zip

    steps:
      - uses: actions/checkout@v2

      - name: Install cross toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.gcc_pkg }} zip
          rustup target add ${{ matrix.rust_target }}

      - name: Build
        env:
          ${{ matrix.cc_var }}: ${{ matrix.cc_bin }}
          ${{ matrix.cxx_var }}: ${{ matrix.cxx_bin }}
          ${{ matrix.ar_var }}: ${{ matrix.ar_bin }}
          RUSTFLAGS: "-C linker=${{ matrix.cc_bin }}"
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: |
          cargo build --release --no-default-features --features "file-browser sdl2-bundled" \
            --target=${{ matrix.rust_target }} -p desktop

      - name: Prepare release
        run: |
          mkdir -p dist
          cp target/${{ matrix.rust_target }}/release/gmboy dist/

      - name: Zip release
        run: cd dist && zip -r ${{ matrix.out_name }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out_name }}
          path: dist/${{ matrix.out_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.out_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
