name: Build Releases

on:
  push:
    branches:
      - "*"
  release:
    types: [published]

jobs:
  build-linux:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
      - run: cargo build --release
      - uses: softprops/action-gh-release@v2
        with:
          files: target/release/gmboy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
