[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[features]
default = ["filepicker"]
filepicker = []

[dependencies]
core = { path = "../core" }
sdl2 = { version = "0.38", default-features = false, features = ["unsafe_textures"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
rfd = "0.15.4" # tinyfiledialogs = "3.9"

[target.'cfg(target_os="macos")'.dependencies.sdl2]
features=["bundled", "static-link"]
version="0.38"

[[bin]]
name = "gmboy"
path = "src/main.rs"