[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[dependencies]
core = { path = "../core" }
rfd = "0.15.*"
sdl2 = { version = "0.38.*", default-features = false, features = ["unsafe_textures"] } #"bundled"

[[bin]]
name = "gmboy"
path = "src/main.rs"