[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[features]
default = ["filepicker"]
filepicker = ["tinyfiledialogs"]

[dependencies]
app = { path = "../app" }
tinyfiledialogs = { version = "3.9", optional = true }

[[bin]]
name = "gmboy"
path = "src/main.rs"