[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
authors = ["troidem <mxmgorin@gmail.com>"]

[features]
default = ["filepicker"]
filepicker = []

[dependencies]
app = { path = "../app" }

[[bin]]
name = "gmboy"
path = "src/main.rs"